#!/bin/bash
sudo docker run -it --rm \
                    -u "$(id -u)":"$(id -g)" \
                    -v /etc/passwd:/etc/passwd:ro \
                    -v /etc/group:/etc/group:ro \
                    -v "$(pwd)":/app \
                    composer/composer "$@"
